# Generated by Django 2.0.4 on 2018-04-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_coinpayments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpaymentstransaction',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
