# Generated by Django 3.2.10 on 2022-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_coinpayments', '0002_auto_20180428_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Buyer email'),
        ),
    ]
